apiVersion: v1
kind: ConfigMap
metadata:
  name: sidecar-injector-webhook-configmap
data:
  sidecarconfig.yaml: |
    containers:
      - name: webhook-injected-cloudlens-sidecar
        image: ixiacom/cloudlens-agent:latest
        imagePullPolicy: Always
        env:
          - name: CLOUDLENS_API_KEY
            valueFrom:
              secretKeyRef:
                name: cloudlens-config-secret
                key: apikey
        args:
          - "--accept_eula"
          - "yes"
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
              - SYS_ADMIN
              - SYS_RAWIO
              - SYS_RESOURCE
