apiVersion: v1
kind: Service
metadata:
  labels:
    run: dsvw-deployment
  name: dsvw-deployment
spec:
  clusterIP: 10.102.36.91
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31418
    port: 80
    protocol: TCP
    targetPort: 6200
  selector:
    run: dsvw-deployment
  sessionAffinity: None
  type: NodePort